### ISSUE TITLE
AppRouter模式好像还不行？

### ISSUE THREAD

**Issue by Issho-lin** [ant-design/ant-design-examples#10]

**Comment by Tongyaoyu** [comment]
同问app router模式该怎么处理

**Comment by Kaempy** [comment]
### How do I configure Ant Design with the new App Directory in NextJs 13

> Hello, Please how do I configure ant design initialization and setup in the new and recommended NextJs 13 app directory and also how do I prevent UI shift on first render in the new NextJs13 app directory.

**Comment by conioX** [comment]
can we have official implementation with app router

**Comment by jin-benben** [comment]
mark

**Comment by TLovers** [comment]
APP路由怎么自定义主题啊 ，按照官网https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B8%B2%E6%9F%93 生成css 后自定义的主题还是无效的啊

**Comment by MadCcc** [comment]
Supported after antd@5.7.1
https://github.com/ant-design/ant-design-examples/blob/main/examples/with-nextjs-app-router-inline-style/src/app/page.tsx

Notice that because of check of nextjs, sub component used with dot still need declare `'use client'` in page.

**Comment by Sherryme** [comment]
> Supported after antd@5.7.1 https://github.com/ant-design/ant-design-examples/blob/main/examples/with-nextjs-app-router-inline-style/src/app/page.tsx
> 
> Notice that because of check of nextjs, sub component used with dot still need declare `'use client'` in page.

I see it say I need to add `use client` if I use sub-components : https://github.com/ant-design/ant-design-examples/blob/main/examples/with-nextjs-app-router-inline-style/src/app/with-sub-components/page.tsx . but after I add it, how do I fetch data on the server? I asked at https://github.com/ant-design/ant-design-examples/issues/24
