### ISSUE TITLE
with-nextjs-app-router-inline-style Demo 渲染出的HTML包含两份同样的内嵌Style。

### ISSUE THREAD

**Issue by rocketxujia** [ant-design/ant-design-examples#32]
启动 with-nextjs-app-router-inline-style Demo 后，查看页面源码，可以看到有两个相同内容的 <style id="antd"> 样式节点（造成html文件变大一倍）。如下图：

<img width="1042" alt="Screenshot 2023-09-28 at 3 42 00 PM" src="https://github.com/ant-design/ant-design-examples/assets/423613/b0e6786f-7e57-4268-9e9d-4e3ffa6ffde5">

问下，有解决方案处理吗？

**Comment by blockmood** [comment]
我也是碰到了这个问题， 请问解决了吗

**Comment by blockmood** [comment]
@rocketxujia

**Comment by blockmood** [comment]
https://github.com/ant-design/ant-design/issues/45567

**Comment by MadCcc** [comment]
`useServerInsertedHTML` 会重复插入的问题，推荐使用 `@ant-design/nextjs-registry`
